hwi_oauth:
    # https://github.com/hwi/HWIOAuthBundle/blob/master/docs/2-configuring_resource_owners.md
    resource_owners:
        vkontakte:
            type:                vkontakte
            client_id:           '%env(OAUTH_VK_CLIENT_ID)%'
            client_secret:       '%env(OAUTH_VK_CLIENT_SECRET)%'
            scope:               "email phone"